apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      initContainers:
        - name: wait-for-db-init
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 postgres 5432; do echo "Waiting for database connection..."; sleep 5; done;' ]
      containers:
      - name: scheduler
        image: my_airflow:2.7.1
        imagePullPolicy: IfNotPresent
        command: ["airflow", "scheduler"]
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        volumeMounts:
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        - name: airflow-dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: airflow-logs
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: airflow-dags
