FROM jupyterhub/jupyterhub:3.1.1


WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

VOLUME ["/app/notebooks", "/app/src", "/app/data"]

RUN pip install -r /app/requirements.txt


ENTRYPOINT jupyterhub --log-level=DEBUG
